apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: mysql
  namespace: tbs-demo
spec:
  tag: harbor2.lab.home:30003/tbs/mysql
  serviceAccount: default
  builder:
    name: demo-custom-builder
    kind: CustomBuilder
    cacheSize: "1.5Gi"
  source:
    git:
      url: https://github.com/techgnosis/pas-golang-mysql.git
      revision: demo

